AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Bun runtime packaged as a Lambda layer.

Parameters:
  BunVersion:
    Type: String
    Description: The version of Bun
    Default: 'latest'

Resources:
  BunLayerArm64:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BunRuntimeArm64
      Description: !Sub "Bun runtime v${BunVersion} (ARM64)"
      ContentUri: ./bun-layer-arm64.zip
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/sumcoding/bun-runtime/blob/main/LICENSE
      RetentionPolicy: Retain

  BunLayerX64:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BunRuntimeX64
      Description: !Sub "Bun runtime v${BunVersion} (x64)"
      ContentUri: ./bun-layer-x64.zip
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/sumcoding/bun-runtime/blob/main/LICENSE
      RetentionPolicy: Retain

Outputs:
  BunVersion:
    Description: The version of Bun
    Value: !Ref BunVersion
    Export:
      Name: BunVersion

  BunLayerArm64:
    Description: Bun runtime (ARM64)
    Value: !Ref BunLayerArm64
    Export:
      Name: BunLayerArm64

  BunLayerX64:
    Description: Bun runtime(x64)
    Value: !Ref BunLayerX64
    Export:
      Name: BunLayerX64

Metadata:
  AWS::ServerlessRepo::Application:
    Name: bun-runtime
    Description: >
      Bun runtime packaged as a Lambda layer.
      Bundles Bun runtime for ARM64 and x64 architectures.
    Author: Summer Phillips
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: PUBLISH.md
    Labels: ['layer', 'bun', 'lambda', 'bun-runtime']
    HomePageUrl: https://github.com/sumcoding/bun-runtime
    SemanticVersion: !Ref BunVersion
    SourceCodeUrl: https://github.com/sumcoding/bun-runtime
