AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Bun runtime packaged as a Lambda layer.

Parameters:
  BunVersion:
    Type: String
    Description: The version of Bun
    Default: 'latest'

Resources:
  BunLayerArm64:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BunRuntimeArm64
      Description: !Sub "Bun runtime v${BunVersion} (ARM64)"
      ContentUri: ./bun-layer-arm64.zip
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/sumcoding/bun-runtime/blob/main/LICENSE
      RetentionPolicy: Retain

  BunLayerX64:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BunRuntimeX64
      Description: !Sub "Bun runtime v${BunVersion} (x64)"
      ContentUri: ./bun-layer-x64.zip
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - provided
      LicenseInfo: https://github.com/sumcoding/bun-runtime/blob/main/LICENSE
      RetentionPolicy: Retain

  BunLayerX64VersionPermission:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref BunLayerX64
      Principal: '*'

  BunLayerArm64VersionPermission:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref BunLayerArm64
      Principal: '*'

Outputs:
  BunVersion:
    Description: The version of Bun
    Value: !Ref BunVersion
    Export:
      Name: BunVersion

  BunLayerArm64:
    Description: Bun runtime (ARM64)
    Value: !Ref BunLayerArm64
    Export:
      Name: BunLayerArm64

  BunLayerX64:
    Description: Bun runtime(x64)
    Value: !Ref BunLayerX64
    Export:
      Name: BunLayerX64
